### ISSUE TITLE
Form javascript

### ISSUE THREAD

**Issue by ilumii** [ilumii/TTP_DOM_2#3]
- In a Javascript file, write a program which checks the following things:
checks that the password is 12345678
- if the password is incorrect, send an alert message
- Your page should also include an < h1>tag. If the information in the form is correct, have Javascript change the text in the < h1>.HTML page. It should include inputs for a username, email, and password. Also a submit button.

**Comment by NapatKarm** [comment]
Form javascript has been created. In the form "password.js"
